#!/usr/bin/env python3
"""Generate the derived turret pitch-limit lookup used by the UI runtime."""

from __future__ import annotations

import argparse
from pathlib import Path
import xml.etree.ElementTree as ET


TURRET_CLASSES = {"turret", "missileturret"}


def number(value: str) -> float:
    return float(value)


def lua_number(value: float) -> str:
    return str(int(value)) if value.is_integer() else format(value, ".15g")


def xml_files(root: Path):
    yield from sorted(root.rglob("*.xml"))


def main() -> int:
    parser = argparse.ArgumentParser(
        description="derive turret rotation_x limits from unpacked official X4 assets"
    )
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--x4-version", required=True)
    parser.add_argument("roots", nargs="+", type=Path)
    args = parser.parse_args()

    components: dict[str, tuple[float, float]] = {}
    for root in args.roots:
        if not root.is_dir():
            parser.error(f"not a directory: {root}")
        for path in xml_files(root):
            if "macros" in path.parts:
                continue
            try:
                document = ET.parse(path)
            except ET.ParseError as error:
                raise SystemExit(f"invalid XML {path}: {error}") from error
            for component in document.findall(".//component"):
                if component.get("class") not in TURRET_CLASSES:
                    continue
                name = component.get("name")
                if not name:
                    continue
                yaw_restrictions = component.findall(
                    ".//restriction[@type='rotation_y']"
                )
                if len(yaw_restrictions) != 1:
                    raise SystemExit(
                        f"expected exactly one turret yaw restriction in {path}: "
                        f"{name} has {len(yaw_restrictions)}"
                    )
                if yaw_restrictions[0].find("limits") is not None:
                    raise SystemExit(
                        f"unsupported bounded turret yaw in {path}: {name}"
                    )
                pitch_limits: list[tuple[float, float]] = []
                for limits in component.findall(
                    ".//restriction[@type='rotation_x']/limits"
                ):
                    minimum = limits.find("min")
                    maximum = limits.find("max")
                    if minimum is None or maximum is None:
                        continue
                    pitch_limits.append(
                        (number(minimum.attrib["value"]), number(maximum.attrib["value"]))
                    )
                if not pitch_limits:
                    raise SystemExit(
                        f"missing bounded turret pitch restriction in {path}: {name}"
                    )
                if any(pair != pitch_limits[0] for pair in pitch_limits[1:]):
                    raise SystemExit(
                        f"non-identical turret pitch limits in {path}: {name} {pitch_limits}"
                    )
                previous = components.get(name)
                if previous is not None and previous != pitch_limits[0]:
                    raise SystemExit(
                        f"conflicting component limits for {name}: {previous} vs {pitch_limits[0]}"
                    )
                components[name] = pitch_limits[0]

    macros: dict[str, tuple[float, float]] = {}
    unresolved: list[str] = []
    for root in args.roots:
        for path in xml_files(root):
            if "macros" not in path.parts:
                continue
            document = ET.parse(path)
            for macro in document.findall(".//macro"):
                if macro.get("class") not in TURRET_CLASSES:
                    continue
                name = macro.get("name")
                component = macro.find("component")
                component_name = component.get("ref") if component is not None else None
                if not name or not component_name:
                    continue
                limits = components.get(component_name)
                if limits is None:
                    unresolved.append(f"{name} -> {component_name}")
                    continue
                previous = macros.get(name)
                if previous is not None and previous != limits:
                    raise SystemExit(
                        f"conflicting macro limits for {name}: {previous} vs {limits}"
                    )
                macros[name] = limits

    if unresolved:
        raise SystemExit("unresolved turret macros:\n  " + "\n  ".join(sorted(unresolved)))
    if not macros:
        raise SystemExit("no turret macros found")

    lines = [
        "-- Generated by scripts/generate-turret-arc-limits.py from official",
        f"-- X4 {args.x4_version} WeaponSystems XML. Values are degrees in the",
        "-- turret component's fixed mount frame; do not hand-edit.",
        "X4GunneryTurretArcLimits = {",
    ]
    for name, (minimum, maximum) in sorted(macros.items()):
        lines.append(
            f'    ["{name}"] = {{ {lua_number(minimum)}, {lua_number(maximum)} }},'
        )
    lines.extend(["}", ""])
    args.output.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {len(macros)} turret macro limits to {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
