#!/usr/bin/env python3
"""Generate the single source-resolved turret muzzle geometry consumed by UI Lua."""
from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Sequence

from census_common import CensusError
from census_pipeline import build_census


MACRO = "turret_par_l_beam_01_mk1_macro"
SEMANTIC_CASE = "depth4_dual_translation"


def _source_set(value: str) -> tuple[str, Path]:
    if "=" not in value:
        raise argparse.ArgumentTypeError("expected NAME=PATH")
    name, raw_path = value.split("=", 1)
    if not name or not raw_path:
        raise argparse.ArgumentTypeError("expected non-empty NAME=PATH")
    return name, Path(raw_path)


def _mapping(values: list[tuple[str, Path]], option: str) -> dict[str, Path]:
    result: dict[str, Path] = {}
    for name, path in values:
        if name in result:
            raise SystemExit(f"duplicate {option} name: {name}")
        result[name] = path
    return result


def _number(value: object) -> str:
    number = float(value)
    if number == 0:
        return "0"
    return repr(number)


def _vector(offset: dict[str, object], key: str, names: tuple[str, ...]) -> str:
    record = offset.get(key)
    if record is None:
        defaults = (0.0, 0.0, 0.0, 1.0) if key == "quaternion" else (0.0, 0.0, 0.0)
        values = defaults
    else:
        values = tuple(float(record[name]["candidate_numeric_value"]) for name in names)
    return "{ " + ", ".join(_number(value) for value in values) + " }"


def _transform(offset: dict[str, object]) -> str:
    return "{ position = %s, quaternion = %s }" % (
        _vector(offset, "position", ("x", "y", "z")),
        _vector(offset, "quaternion", ("qx", "qy", "qz", "qw")),
    )


def _rotation(restrictions: list[dict[str, object]]) -> str | None:
    if not restrictions:
        return None
    if len(restrictions) != 1:
        raise SystemExit("unsupported multiple runtime rotation roles on one layer")
    restriction = restrictions[0]
    token = str(restriction["type_token"])
    if token not in ("rotation_x", "rotation_y"):
        raise SystemExit(f"unsupported runtime rotation role: {token}")
    fields = [f'axis = "{token[-1]}"']
    for source, target in (("authored_min", "minimum_degrees"), ("authored_max", "maximum_degrees")):
        bound = restriction.get(source)
        if bound is not None:
            fields.append(f'{target} = {_number(bound["candidate_numeric_value"])}')
    return "{ " + ", ".join(fields) + " }"


def _render(report: dict[str, object], x4_version: str) -> str:
    if str(report["x4_version"]) != x4_version:
        raise SystemExit(
            f"census X4 version {report['x4_version']} does not match {x4_version}"
        )
    matches = [
        record
        for record in report["component_to_macros"]
        if MACRO in record["macros"]
    ]
    if len(matches) != 1 or matches[0]["macros"].count(MACRO) != 1:
        raise SystemExit(f"expected exactly one census identity for {MACRO}")
    component = matches[0]
    if component["macros"] != [MACRO]:
        raise SystemExit(f"unsupported shared component for {MACRO}")
    resolutions = component["source_semantic_resolutions"]
    if len(resolutions) != 2 or any(
        item.get("classification") != "SOURCE_RESOLVED"
        or item.get("semantic_case") != SEMANTIC_CASE
        for item in resolutions
    ):
        raise SystemExit(f"unsupported source geometry for {MACRO}")

    geometries = [item["applied_authored_geometry"] for item in resolutions]
    layers = geometries[0]["source_geometry_layers"]
    if len(layers) != 4 or any(
        geometry["source_geometry_layers"] != layers for geometry in geometries[1:]
    ):
        raise SystemExit(f"unsupported endpoint topology for {MACRO}")

    lines = [
        "-- Generated by scripts/generate-turret-muzzle-geometry.py from the",
        f"-- X4 {x4_version} census source-semantic pipeline; do not hand-edit.",
        "X4GunneryTurretMuzzleGeometry = {",
        f'    ["{MACRO}"] = {{',
        f'        semantic_case = "{SEMANTIC_CASE}",',
        "        layers = {",
    ]
    for layer in layers:
        lines.extend([
            "            {",
            f'                source_part = "{layer["source_part"]}",',
            f'                owning_connection = "{layer["owning_connection"]}",',
            f'                connection_transform = {_transform(layer["connection_authored_offset"])},',
            f'                part_transform = {_transform(layer["part_authored_offset"])},',
        ])
        if "settled_local_position_delta" in layer:
            values = layer["settled_local_position_delta"]
            lines.append(
                "                settled_position = { "
                + ", ".join(_number(value) for value in values)
                + " },"
            )
        rotation = _rotation(layer["authored_restrictions"])
        if rotation is not None:
            lines.append(f"                runtime_rotation = {rotation},")
        lines.append("            },")
    lines.extend(["        },", "        endpoints = {"])
    for geometry in sorted(geometries, key=lambda item: item["endpoint_connection"]):
        lines.append(
            f'            {{ connection = "{geometry["endpoint_connection"]}", '
            f'transform = {_transform(geometry["endpoint_authored_offset"])} }},'
        )
    lines.extend(["        },", "    },", "}", ""])
    return "\n".join(lines)


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description=f"generate source-resolved muzzle geometry for {MACRO}"
    )
    parser.add_argument("--source-set", action="append", default=[], type=_source_set)
    parser.add_argument("--resource-set", action="append", default=[], type=_source_set)
    parser.add_argument("--x4-version", required=True)
    parser.add_argument("--output", required=True, type=Path)
    args = parser.parse_args(argv)
    try:
        report = build_census(
            _mapping(args.source_set, "source-set"),
            _mapping(args.resource_set, "resource-set"),
            include_source_semantic_resolutions=True,
        )
    except CensusError as error:
        print(error, file=sys.stderr)
        return 1
    args.output.write_text(_render(report, args.x4_version), encoding="utf-8")
    print(f"wrote 1 turret macro geometry record to {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
