-- Issue #202: real ui/gunnery_control.lua selected-target pass behavior, run
-- through the shared runtime fixture. Complements the permanent case in
-- tests/test_runtime_targeting_surface.lua; SPEC rows are #202 task 3 targets
-- that the code under test may not implement yet.
--   lua research/issue202-line-of-fire/runtime.lua

local fix = dofile("tests/support/runtime_fixture.lua").load()
local API, C = fix.API, fix.C
local clock = 100
getElapsedTime = function() return clock end
fix.gcMenu.onShowMenu()

local session = API.getSession()
session.phase, session.controlMode = "target_select", nil
local selected = 730
C.GetSofttarget2 = function() return { softtargetID = selected, softtargetConnectionName = "" } end
local members = {}
for i = 1, 3 do members[i] = { componentID = 3000 + i, operational = true } end
session.groups = {{ key = "g", members = members }}
session.checkedGroupKeys = { g = true }

local events, ranges = {}, {}
AddUITriggeredEvent = function(_, control, params)
    if control:match("^line_of_fire") then events[#events + 1] = { control = control, params = params }
    elseif control:match("^in_range") then ranges[#ranges + 1] = control end
end
local function last() return events[#events].params end
local function reply(status, calls, request, reason)
    request = request or last()
    fix.fireEvent("X4GunneryControl.LineOfFireResult", "x4gcl1:" .. request.nonce .. ":" .. request.weaponid
        .. ":" .. status .. ":" .. (reason or "") .. ":" .. calls)
end
local function pass(statuses)
    for _, s in ipairs(statuses) do
        API.runClearPass(clock)
        reply(s[1], s[2], nil, s[3])
    end
end

local rows, failed = {}, 0
local function check(kind, name, ok, detail)
    rows[#rows + 1] = string.format("%-4s %-5s %s%s", ok and "PASS" or "FAIL", kind, name,
        ok and "" or ("  -- " .. tostring(detail)))
    if not ok and kind == "CODE" then failed = failed + 1 end
end

-- IN RANGE owns membership and selection only; its sweep may be mid-flight.
API.setRangeTargets({ 730, 731 }, 730)
API.runRangeSweep(clock)
local rangeRequests = #ranges
API.runClearPass(clock)
API.runClearPass(clock)
check("CODE", "pass starts while an IN RANGE request is outstanding, one turret per request",
    #events == 2 and events[1].control == "line_of_fire_begin" and last().weaponid == "3001", #events)
reply("C", 1)
reply("C", 1)
API.runClearPass(clock)
check("CODE", "duplicated response is ignored and the next turret is requested",
    last().weaponid == "3002", last().weaponid)
reply("G", 0)
API.runClearPass(clock)
reply("U", 0, nil, "frame")
local text, paths = API.clearText(730)
check("CODE", "vanished component (MD frame UNKNOWN) still completes the pass",
    paths == "BLOCKED PATH 0   UNKNOWN 1   GUIDED 1", paths)
check("CODE", "no IN RANGE traffic is generated by the selected-target pass", #ranges == rangeRequests, #ranges)
check("SPEC", "GUIDED counts toward CLEAR LINE OF FIRE: 2 / 3", text:match("2 / 3") ~= nil, text)
check("SPEC", "plain ASCII colon, no non-ASCII dash", text:match("^CLEAR LINE OF FIRE: ") ~= nil
    and not text:find("[\128-\255]"), text)
check("CODE", "another target's display never shows this result",
    API.clearText(731) == API.clearText(0) and not API.clearText(731):match("%d / %d"), API.clearText(731))

-- Membership change mid-pass discards the active pass and its late reply.
clock = clock + 2.5
API.runClearPass(clock)
local before = last()
session.groups[1].members = { members[1], members[2] }
API.setRangeTargets({ 730, 731 }, 730)
reply("B", 3, before)
API.runClearPass(clock)
check("CODE", "turret-membership change drops the in-flight pass and restarts",
    events[#events - 1].control == "line_of_fire_begin" and last().nonce ~= before.nonce, last().nonce)
check("CODE", "completed result is not reused after a membership change",
    not API.clearText(730):match("%d / %d"), API.clearText(730))
reply("C", 1)
pass({ { "B", 3 } })
check("CODE", "new pass completes over the new two-turret membership only",
    API.clearText(730):match("1 / 2") ~= nil, API.clearText(730))

-- Refresh keeps the last complete result; a new selection hides it at once.
clock = clock + 2.5
API.runClearPass(clock)
local refreshing = last()
check("CODE", "last complete result stays visible while refreshing",
    API.clearText(730):match("1 / 2") ~= nil, API.clearText(730))
selected = 731
API.setRangeTargets({ 730, 731 }, 731)
reply("C", 1, refreshing)
check("NOTE", "Clear.text itself hides the old result before the next update",
    not API.clearText(730):match("%d / %d"), API.clearText(730))
API.runClearPass(clock)
check("CODE", "old selection's result is discarded on the next update",
    not API.clearText(730):match("%d / %d") and not API.clearText(731):match("%d / %d"), API.clearText(730))

-- A late reply after a timeout, and a reply from another session, are ignored.
API.runClearPass(clock)
API.runClearPass(clock)
local timed = last()
clock = clock + 2.1
API.runClearPass(clock)
reply("C", 1, timed)
check("CODE", "reply after the 2 s timeout is ignored and publishes nothing",
    fix.logContains("event=line_of_fire action=timeout") and not API.clearText(731):match("%d / %d"),
    API.clearText(731))

-- One turret that never answers times out and restarts the whole pass each time.
for _ = 1, 3 do
    clock = clock + 2.5
    API.runClearPass(clock)
    reply("C", 1)
    API.runClearPass(clock)
    clock = clock + 2.1
    API.runClearPass(clock)
end
check("NOTE", "a result still publishes when one turret never answers",
    API.clearText(731):match("%d / %d") ~= nil, API.clearText(731))

-- Paused games and non-direct engaged sessions send no requests.
local sent = #events
C.IsGamePaused = function() return true end
clock = clock + 2.5
API.runClearPass(clock)
C.IsGamePaused = function() return false end
session.phase, session.controlMode = "engaged", "turret"
API.runClearPass(clock)
check("CODE", "no request while paused or engaged outside direct control", #events == sent, #events - sent)
session.phase, session.controlMode = "target_select", nil
clock = clock + 2.5
API.runClearPass(clock)
reply("C", 1)
API.runClearPass(clock)
local old = last()
session.phase = "console"
fix.gcMenu.onCloseElement("close")
reply("C", 1, old)
check("CODE", "final reply after the session ends publishes nothing",
    API.getSession() == nil and not API.clearText(731):match("%d / %d"), API.clearText(731))

for _, row in ipairs(rows) do print(row) end
if failed > 0 then os.exit(1) end
