"""Issue #184 A8 (temporary): record the frozen A7.3 search on a few real targets, in the target's own
frame, as a Lua fixture for the Test Lab port.

The live A8 question is asked in target-local space, so each view uses the identity target rotation.
Every oracle call is recorded in order, so the Lua port must ask exactly the same positions and finish
with the same points and refined estimates.

    python3 research/issue184/a8_trace.py   # writes tests/fixtures/issue184_a8_traces.lua
"""
import numpy as np

import aimpoint_map as m

CASES = ("ship_arg_xl_carrier_02", "ship_arg_l_destroyer_02", "ship_bor_l_miner_liquid_01")  # 4, 3, 2 points
OUT = m.ROOT / "tests/fixtures/issue184_a8_traces.lua"


def num(x):
    return repr(float(x))


def vec(v):
    return "{" + ", ".join(num(x) for x in v) + "}"


def trace(t):
    oracle, asks = m.oracle(dict(points=t["points"], box=(t["C"], t["H"], np.eye(3)))), []

    def ask(u):
        d = oracle(u)
        asks.append((u, d))
        return d
    st = m.near_only_run(dict(oracle=ask, target_box=(t["C"], t["H"], np.eye(3))),
                         total=m.A73_TOTAL, pad=m.A6_NEAR_PAD, geom=m.A73_GEOM)
    pts = [(np.asarray(x, float), r) for x, r in st["points"]]
    refined, _n, _why = m.refine_points(pts, st["rays"])
    return asks, st, pts, refined


def main():
    by = {t["component"]: t for t in m.targets()}
    out = ["-- Generated by research/issue184/a8_trace.py; do not edit. Temporary #184 A8 fixture.", "return {"]
    one = min(n for n, t in by.items() if n.startswith("ship_") and len(t["points"]) == 1)
    zero = ("zero_authored", dict(by[CASES[0]], points=[]))  # the carrier box, X4's empty-collection fallback
    for name, t in [(n, by[n]) for n in CASES + (one,)] + [zero]:
        asks, st, pts, refined = trace(t)
        out.append(f"  {{ name = {name!r}, C = {vec(t['C'])}, H = {vec(t['H'])}, authored = {len(t['points'])},")
        out.append(f"    stop = {st['end']!r}, samples = {st['asks']},")
        out.append("    asks = {")
        out += [f"      {{ p = {vec(u)}, d = {'nil' if d is None else vec(d)} }}," for u, d in asks]
        out.append("    },")
        out.append("    found = {" + ", ".join(f"{{{n}, {k}}}" for n, k in st["found"]) + "},")
        out.append("    points = {" + ", ".join(f"{{ c = {vec(c)}, r = {num(r)} }}" for c, r in pts) + "},")
        out.append("    refined = {" + ", ".join(f"{{ c = {vec(c)}, r = {num(r)} }}" for c, r in refined) + "},")
        out.append("  },")
        print(f"{name}: {len(t['points'])} authored, {st['asks']} samples, {len(pts)} points, end {st['end']}")
    out.append("}")
    OUT.write_text("\n".join(out) + "\n")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
