-- Generated by scripts/generate-turret-muzzle-geometry.py from the
-- X4 9.00 census source-semantic pipeline; do not hand-edit.
X4GunneryTurretMuzzleGeometry = {
    ["turret_par_l_beam_01_mk1_macro"] = {
        semantic_case = "depth4_dual_translation",
        layers = {
            {
                source_part = "part_socket",
                owning_connection = "Connection01",
                connection_transform = { position = { 1.877547e-06, 2.018104, -1.043081e-05 }, quaternion = { 0, 0, 0, 1.0 } },
                part_transform = { position = { 0, 0, 0 }, quaternion = { 0, 0, 0, 1.0 } },
            },
            {
                source_part = "part_rotator",
                owning_connection = "Connection03",
                connection_transform = { position = { 0, 0, 0 }, quaternion = { 0, 0, 0, 1.0 } },
                part_transform = { position = { 0, 0, 0 }, quaternion = { 0, 0, 0, 1.0 } },
                settled_position = { 0, 6.145042419433594, 0 },
                runtime_rotation = { axis = "y" },
            },
            {
                source_part = "anim_gun",
                owning_connection = "Connection04",
                connection_transform = { position = { -1.730653e-06, 2.926126, -16.11956 }, quaternion = { -0.004327158, 3.273904e-12, -7.565876e-10, 0.9999906 } },
                part_transform = { position = { 0, 0, 0 }, quaternion = { 0, 0, 0, 1.0 } },
                runtime_rotation = { axis = "x", minimum_degrees = -5.0, maximum_degrees = 80.0 },
            },
            {
                source_part = "anim_barrel",
                owning_connection = "Connection05",
                connection_transform = { position = { -1.113896e-06, 0.06259775, 17.45395 }, quaternion = { 0.004327045, -6.547686e-12, 2.825544e-14, 0.9999906 } },
                part_transform = { position = { 0, 0, 0 }, quaternion = { 0, 0, 0, 1.0 } },
                settled_position = { 0, -0.23982000350952148, 27.710205078125 },
            },
        },
        endpoints = {
            { connection = "con_laser_01", transform = { position = { 0.3332827, 0.2692866, 10.70685 }, quaternion = { 0, 0, 0, 1.0 } } },
            { connection = "con_laser_02", transform = { position = { -0.361773, 0.2692866, 10.70685 }, quaternion = { 0, 0, 0, 1.0 } } },
        },
    },
}
